version: '3.8'

services:
  thenorth-database:
    image: mariadb:lts
    container_name: thenorth-database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - 3306:3306
      # - 33060:33060
    volumes:
      - mysql-data:/var/lib/mysql

  thenorth-backend:
    depends_on:
      - thenorth-database
    container_name: thenorth-backend
    build:
      context: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - $DEBUG_LOCAL_PORT:$DEBUG_DOCKER_PORT
    environment:
      - SERVER_PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - $NODE_DOCKER_PORT
    command: npm run start
    stdin_open: true
    tty: true
    # command: ls -lah

  thenorth-adminer:
    image: adminer
    container_name: thenorth-adminer
    depends_on:
      - thenorth-database
    ports:
      - 8080:8080

volumes:
  mysql-data:
